# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Critical Section
email: 
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog for artificial intelligence and similar topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: 
github_username:  aceofgreens

# Build settings
theme: minima
plugins:
  - jekyll-feed

# highlighter: rouge
markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
    # block:
      # line_numbers: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

domain: aceofgreens.github.io
url: https://aceofgreens.github.io
baseurl: /
# excerpt_separator: <--end excerpt-->

